version: '3.8' 

services:
  sveltekit:
    image: node:18-alpine  
    working_dir: /app
    ports:
      - "5173:5173" 
    volumes:
      - .:/app  
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
    command: >
      sh -c "rm -rf node_modules package-lock.json && npm install && npm run dev -- --host --open"

  # Not currently working
  firebase-emulator:
    image: node:18-alpine  
    volumes:
      - .:/app
      - ~/.config/firebase:/root/.config/firebase  
    working_dir: /app
    ports:
      - "9099:9099"  
    command: >
      sh -c "npm install -g firebase-tools && firebase emulators:start --only auth --host 0.0.0.0"